name = "open_coords"
type = "webpack"
account_id = "86a23d741c87821746178bdf783d48cf"
workers_dev = true
usage_model = ''
compatibility_flags = []
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-10-11"

[env.production]
workers_dev = false
route = "https://opencoordinates.com/"
zone_id = "d62ff18d48e420a65de106a3ee79607e"


